commit feedback
vupham3001/hapolearn pull request #15
Opened 2021-08-20 08:15 UTC by vupham3001

2021-08-22 06:24 UTC, hapo-nghialuu commented on index.html
> +                    <div class="container justify-content-center mt-5 border-left border-right carousel-item active">
sao dùng lắm cointainer như thế này?

2021-08-22 06:26 UTC, hapo-nghialuu commented on index.html
> +                    <div class="container justify-content-center mt-5 border-left border-right carousel-item">
dùng cointainer linh tinh quá

2021-08-22 06:27 UTC, hapo-nghialuu commented on javascript/index.js
> +$('.carousel.slide').slick({
chưa đặt phần js này trong document ready của jquery

2021-08-22 06:28 UTC, hapo-nghialuu commented on javascript/index.js
> +$('.carousel.slide').slick({
thêm nữa selector này: `.carousel.slide` đã chọn đúng element chứa các phần tử trong list chưa?

2021-08-24 01:44 UTC, hapo-huypv commented on index.html
> +                        <a href="" class="mr-auto contact">
chưa add link

2021-08-24 01:44 UTC, hapo-huypv commented on index.html
> +                            <i class="fas fa-envelope footer-icon"></i>
dùng ảnh thì đỡ phải chỉnh sửa nhé

2021-08-24 01:50 UTC, vominhmanh reviewed
Minh Manh has some comments

2021-08-24 01:50 UTC, vominhmanh commented on index.html
> +            <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
Đổi tên id đi ông nhé

2021-08-24 01:50 UTC, vominhmanh commented on index.html
> +                        <a href="">
href trống thì ông có thể điền dấu #

2021-08-24 01:50 UTC, vominhmanh commented on index.html
> +                            <p><a href="" class="footer-text">Blog</a></p>
href thì điền dấu # vào ông nhé, đừng để trống

2021-08-24 01:50 UTC, vominhmanh commented on javascript/index.js
> +    infinite: false,
ở đây có indent = 4, nhưng phía dưới có indent = 2

2021-08-24 01:52 UTC, vupham3001 commented on index.html
> +                            <i class="fas fa-envelope footer-icon"></i>
oke

2021-08-24 01:56 UTC, vupham3001 commented on index.html
> +            <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
cái id này là copy trên bootstrap, đổi thì nó không chuyển slide được đó ông

2021-08-24 02:06 UTC, vominhmanh requested changes

2021-08-24 02:06 UTC, vominhmanh commented on index.html
> +            <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
```suggestion
            <div id="carouselFeedbackIndicators" class="carousel slide" data-ride="carousel">
```

2021-08-24 02:06 UTC, vominhmanh commented on index.html
> +                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
```suggestion
                    <a class="carousel-control-prev" href="#carouselFeedbackIndicators" role="button" data-slide="prev">
```

2021-08-24 02:06 UTC, vominhmanh commented on index.html
> +                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
```suggestion
                    <a class="carousel-control-next" href="#carouselFeedbackIndicators" role="button" data-slide="next">
```

2021-08-24 02:06 UTC, vominhmanh commented on index.html
> +            <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
ý tôi là sửa id sang đúng tên của phần ông đang làm ấy,

2021-08-24 02:07 UTC, vominhmanh commented on index.html
> +            <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
ý tôi là sửa id sang đúng tên của phần ông đang làm ấy,

2021-08-24 02:18 UTC, vupham3001 commented on index.html
> +            <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
oke ông

2021-08-24 04:38 UTC, hapo-nghialuu commented on index.html
> +                            <p><a href="#" class="footer-text">Home</a></p>
sao cần bọc p ngoài a làm gì nhỉ?

2021-08-24 04:38 UTC, hapo-nghialuu commented on javascript/main.js
> -
file này không dùng thì xóa đi nhé

2021-08-24 04:39 UTC, hapo-nghialuu commented on scss/_feedback.scss
> +}
sao vẫn bị lỗi thiếu enter như thế này nhỉ?

2021-08-24 04:39 UTC, hapo-nghialuu commented on scss/_feedback.scss
> +}
tìm và sửa các phần tương tự nhé

2021-08-24 05:01 UTC, vupham3001 commented on index.html
> +                            <p><a href="#" class="footer-text">Home</a></p>
nếu không dùng thẻ p thì khi mấy chữ courses kia nó ngắn thì courses tiếp theo nó không tự xuống dòng mà nó ở luôn trên dòng trước, em dùng thẻ chiều dài mỗi courses nó bằng luôn chiều dài thẻ div

2021-08-24 06:10 UTC, merged